# Generated by Django 5.0.1 on 2024-01-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_otp_user_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(default='111999', max_length=6),
        ),
    ]
