# Generated by Django 5.0.1 on 2024-01-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email', max_length=50, unique=True),
        ),
    ]
